apiVersion: v1
kind: Service
metadata:
  name: prod-srv
spec:
  type: NodePort
  selector:
    app: prod
  ports: 
    - port: 5000  # accessibilité de ce service depuis l'intérieur du cluster
      targetPort: 5000 # cible l'application serveur conteneurisé dans le pod référencé par ce selector
      nodePort: 30010 # accessibilité pour l'accès depuis l'extérieur du cluster